# -*- coding: utf-8 -*-
"""EDA_MBA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146ngMx7h56tkc3KWitTNMca5OQhuUfbn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.__version__

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MBA.csv',index_col=0, encoding= "utf-8")
df.head() # check the first 5 entries

# settings
colors = ['#78C850',
      '#F08030',
      '#6890F0',
      '#A8B820',
      '#A8A878',
      '#A040A0',
      '#F8D030',
      '#EE99AC',
      '#C03028',
      '#F85888',
      '#B8A038',
      '#705898',
      '#98D8D8',
      '#7038F8',
      ]
sns.set_style('darkgrid')

# addressing null values in race and admission columns
# null/other -> international
# null -> deny
df['race'].fillna('International',inplace=True)
#df['race'].replace('Other','International',inplace=True)
df['admission'].fillna('Deny',inplace=True)

#df['work_industry']=df['work_industry'].astype('category')

df.head()

# check the statistics of admission
plt.figure()
sns.countplot(x='admission',data=df,palette=colors,stat='percent')
plt.title('Admission Statistics')

# Question: does the distribution of working experience differ across different industries？

# work_exp distribution for Non-profit/Gov and other jobs
fig,ax = plt.subplots(2,2,figsize = (6,6)) # 3 rows and 2 columns
plt.subplots_adjust(left=0.1, right=0.9, bottom=0.1, top=0.9, wspace=0.4, hspace=0.4)

sns.countplot(x='work_exp',data=df.loc[df['work_industry']=='Nonprofit/Gov'],palette=colors,stat='percent',ax=ax[0,0])
ax[0,0].set_title('Nonprofit/Gov')


sns.countplot(x='work_exp',data=df.loc[df['work_industry']=='Consulting'],palette=colors,stat='percent',ax=ax[0,1])
ax[0,1].set_title('Consulting')


sns.countplot(x='work_exp',data=df.loc[df['work_industry']=='Technology'],palette=colors,stat='percent',ax=ax[1,0])
ax[1,0].set_title('Technology')


sns.countplot(x='work_exp',data=df.loc[df['work_industry']=='PE/VC'],palette=colors,stat='percent',ax=ax[1,1])
ax[1,1].set_title('PE/VC')

# Observation: no significant difference. We can therefore see that in these industries, people
# start to thinking about pursuing a MBA degree at around the same time: 4-6 years after they
# have worked in this industry.
# We can therefore conclude that promotion rates in these industries are roughly the same: 4-6 years.

grp = df.groupby(['work_exp','admission']).count()['gender']
#df_aug = df
grp2 = df.groupby(['work_exp']).count()['gender']
print(grp2)
exp_ad_dict = dict()
#grp.index

for exp in df['work_exp'].unique():
  total_count = grp2[exp]
  if (exp,'Admit') not in grp.index:
    admit_count = 0
  else:
    admit_count = grp.loc[(exp,'Admit')]
  rate = admit_count/total_count
  exp_ad_dict[exp] = rate

exp_ad_dict = dict(sorted(exp_ad_dict.items(), key=lambda x: x[0]))
exp_ad_dict.pop(1.0)
exp_ad_dict.pop(9.0)

df_aug = pd.DataFrame.from_dict(exp_ad_dict,orient='index')
print(df_aug)
plt.figure()
sns.lineplot(data=df_aug,x=df_aug.index,y=df_aug[0])
plt.xlabel('Work Experience')
plt.ylabel('Admission Rate')
plt.title('Admission Rate vs Work Experience')